# Generated by Django 5.2.3 on 2025-07-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("store", "0002_cart_cartitem_alter_color_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Cart Item", "verbose_name_plural": "Cart Items"},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "color", "size")},
        ),
    ]
