# Generated by Django 5.2.3 on 2025-07-03 11:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="John", max_length=50)),
                ("last_name", models.CharField(default="Doe", max_length=50)),
                (
                    "email",
                    models.EmailField(default="example@example.com", max_length=254),
                ),
                (
                    "phone",
                    models.CharField(
                        default="0000000000",
                        max_length=15,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10, message="Phone number must be at least 10 digits"
                            ),
                            django.core.validators.RegexValidator(
                                message="Phone number must contain only digits",
                                regex="^\\d+$",
                            ),
                        ],
                    ),
                ),
                ("country_code", models.CharField(default="+91", max_length=5)),
                ("country", models.CharField(default="IN", max_length=2)),
                ("state", models.CharField(default="West Bengal", max_length=100)),
                ("street", models.CharField(default="Unknown Street", max_length=200)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("house", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                (
                    "delivery_slot",
                    models.CharField(
                        choices=[
                            ("today_9am_12pm", "Today (9AM - 12PM)"),
                            ("today_6pm_9pm", "Today (6PM - 9PM)"),
                            ("tomorrow_9am_12pm", "Tomorrow (9AM - 12PM)"),
                        ],
                        default="today_9am_12pm",
                        max_length=50,
                    ),
                ),
                ("express_delivery", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("upi", "UPI (Google Pay, PhonePe, Paytm)"),
                            ("credit", "Credit / Debit Card"),
                            ("paypal", "PayPal"),
                            ("cod", "Cash on Delivery"),
                        ],
                        default="upi",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=50)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField(default=0)),
                (
                    "product_name",
                    models.CharField(default="Unknown Product", max_length=200),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="orders/images/"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="orders/images/"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("size", models.CharField(blank=True, max_length=50)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "product_id", "color", "size")},
            },
        ),
    ]
