# Generated by Django 5.2.3 on 2025-07-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_options_alter_orderitem_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="zip_code",
        ),
    ]
