# Generated by Django 5.2.3 on 2025-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
