# Generated by Django 5.2.3 on 2025-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.TextField(blank=True, null=True),
        ),
    ]
