# Generated by Django 5.2.3 on 2025-07-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_is_paid_online_order_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="upi_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gpay", "Google Pay"),
                    ("phonepe", "PhonePe"),
                    ("paytm", "Paytm"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
