# Generated by Django 5.2.3 on 2025-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_upi_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="upi_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google_pay", "Google Pay"),
                    ("phone_pe", "PhonePe"),
                    ("paytm", "Paytm"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
