# Generated by Django 5.2.3 on 2025-07-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_upi_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="upi_method",
        ),
    ]
